// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/movie.proto

package moviepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Movie struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genre                string   `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{0}
}

func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (m *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(m, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movie) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

type CreateMovieRequest struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieRequest) Reset()         { *m = CreateMovieRequest{} }
func (m *CreateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMovieRequest) ProtoMessage()    {}
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{1}
}

func (m *CreateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieRequest.Unmarshal(m, b)
}
func (m *CreateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieRequest.Marshal(b, m, deterministic)
}
func (m *CreateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieRequest.Merge(m, src)
}
func (m *CreateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMovieRequest.Size(m)
}
func (m *CreateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieRequest proto.InternalMessageInfo

func (m *CreateMovieRequest) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type CreateMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieResponse) Reset()         { *m = CreateMovieResponse{} }
func (m *CreateMovieResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMovieResponse) ProtoMessage()    {}
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{2}
}

func (m *CreateMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieResponse.Unmarshal(m, b)
}
func (m *CreateMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieResponse.Marshal(b, m, deterministic)
}
func (m *CreateMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieResponse.Merge(m, src)
}
func (m *CreateMovieResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMovieResponse.Size(m)
}
func (m *CreateMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieResponse proto.InternalMessageInfo

func (m *CreateMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type ReadMovieRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMovieRequest) Reset()         { *m = ReadMovieRequest{} }
func (m *ReadMovieRequest) String() string { return proto.CompactTextString(m) }
func (*ReadMovieRequest) ProtoMessage()    {}
func (*ReadMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{3}
}

func (m *ReadMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMovieRequest.Unmarshal(m, b)
}
func (m *ReadMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMovieRequest.Marshal(b, m, deterministic)
}
func (m *ReadMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMovieRequest.Merge(m, src)
}
func (m *ReadMovieRequest) XXX_Size() int {
	return xxx_messageInfo_ReadMovieRequest.Size(m)
}
func (m *ReadMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMovieRequest proto.InternalMessageInfo

func (m *ReadMovieRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMovieResponse) Reset()         { *m = ReadMovieResponse{} }
func (m *ReadMovieResponse) String() string { return proto.CompactTextString(m) }
func (*ReadMovieResponse) ProtoMessage()    {}
func (*ReadMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{4}
}

func (m *ReadMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMovieResponse.Unmarshal(m, b)
}
func (m *ReadMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMovieResponse.Marshal(b, m, deterministic)
}
func (m *ReadMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMovieResponse.Merge(m, src)
}
func (m *ReadMovieResponse) XXX_Size() int {
	return xxx_messageInfo_ReadMovieResponse.Size(m)
}
func (m *ReadMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMovieResponse proto.InternalMessageInfo

func (m *ReadMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type ReadMoviesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMoviesRequest) Reset()         { *m = ReadMoviesRequest{} }
func (m *ReadMoviesRequest) String() string { return proto.CompactTextString(m) }
func (*ReadMoviesRequest) ProtoMessage()    {}
func (*ReadMoviesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{5}
}

func (m *ReadMoviesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMoviesRequest.Unmarshal(m, b)
}
func (m *ReadMoviesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMoviesRequest.Marshal(b, m, deterministic)
}
func (m *ReadMoviesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMoviesRequest.Merge(m, src)
}
func (m *ReadMoviesRequest) XXX_Size() int {
	return xxx_messageInfo_ReadMoviesRequest.Size(m)
}
func (m *ReadMoviesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMoviesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMoviesRequest proto.InternalMessageInfo

type ReadMoviesResponse struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMoviesResponse) Reset()         { *m = ReadMoviesResponse{} }
func (m *ReadMoviesResponse) String() string { return proto.CompactTextString(m) }
func (*ReadMoviesResponse) ProtoMessage()    {}
func (*ReadMoviesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{6}
}

func (m *ReadMoviesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMoviesResponse.Unmarshal(m, b)
}
func (m *ReadMoviesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMoviesResponse.Marshal(b, m, deterministic)
}
func (m *ReadMoviesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMoviesResponse.Merge(m, src)
}
func (m *ReadMoviesResponse) XXX_Size() int {
	return xxx_messageInfo_ReadMoviesResponse.Size(m)
}
func (m *ReadMoviesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMoviesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMoviesResponse proto.InternalMessageInfo

func (m *ReadMoviesResponse) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type UpdateMovieRequest struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMovieRequest) Reset()         { *m = UpdateMovieRequest{} }
func (m *UpdateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMovieRequest) ProtoMessage()    {}
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{7}
}

func (m *UpdateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMovieRequest.Unmarshal(m, b)
}
func (m *UpdateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMovieRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMovieRequest.Merge(m, src)
}
func (m *UpdateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMovieRequest.Size(m)
}
func (m *UpdateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMovieRequest proto.InternalMessageInfo

func (m *UpdateMovieRequest) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type UpdateMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMovieResponse) Reset()         { *m = UpdateMovieResponse{} }
func (m *UpdateMovieResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMovieResponse) ProtoMessage()    {}
func (*UpdateMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{8}
}

func (m *UpdateMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMovieResponse.Unmarshal(m, b)
}
func (m *UpdateMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMovieResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMovieResponse.Merge(m, src)
}
func (m *UpdateMovieResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMovieResponse.Size(m)
}
func (m *UpdateMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMovieResponse proto.InternalMessageInfo

func (m *UpdateMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type DeleteMovieRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{9}
}

func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(m, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteMovieResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieResponse) Reset()         { *m = DeleteMovieResponse{} }
func (m *DeleteMovieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieResponse) ProtoMessage()    {}
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{10}
}

func (m *DeleteMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieResponse.Unmarshal(m, b)
}
func (m *DeleteMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieResponse.Merge(m, src)
}
func (m *DeleteMovieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieResponse.Size(m)
}
func (m *DeleteMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieResponse proto.InternalMessageInfo

func (m *DeleteMovieResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Movie)(nil), "proto.Movie")
	proto.RegisterType((*CreateMovieRequest)(nil), "proto.CreateMovieRequest")
	proto.RegisterType((*CreateMovieResponse)(nil), "proto.CreateMovieResponse")
	proto.RegisterType((*ReadMovieRequest)(nil), "proto.ReadMovieRequest")
	proto.RegisterType((*ReadMovieResponse)(nil), "proto.ReadMovieResponse")
	proto.RegisterType((*ReadMoviesRequest)(nil), "proto.ReadMoviesRequest")
	proto.RegisterType((*ReadMoviesResponse)(nil), "proto.ReadMoviesResponse")
	proto.RegisterType((*UpdateMovieRequest)(nil), "proto.UpdateMovieRequest")
	proto.RegisterType((*UpdateMovieResponse)(nil), "proto.UpdateMovieResponse")
	proto.RegisterType((*DeleteMovieRequest)(nil), "proto.DeleteMovieRequest")
	proto.RegisterType((*DeleteMovieResponse)(nil), "proto.DeleteMovieResponse")
}

func init() {
	proto.RegisterFile("proto/movie.proto", fileDescriptor_78364ce9948b3a40)
}

var fileDescriptor_78364ce9948b3a40 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xa1, 0xa4, 0xbc, 0x30, 0xf0, 0xaa, 0x2c, 0x26, 0x2e, 0x3d, 0x91, 0x0d, 0x07, 0x4f,
	0x90, 0xe0, 0xc1, 0x3f, 0x17, 0x13, 0x30, 0x78, 0xf2, 0x52, 0xe3, 0xc5, 0x1b, 0xd0, 0x89, 0x69,
	0x82, 0xb4, 0x76, 0x17, 0xbe, 0xb4, 0x5f, 0xc2, 0x74, 0x77, 0xbb, 0xd9, 0x76, 0x7b, 0x10, 0x4f,
	0x30, 0x33, 0xcf, 0xfc, 0xa6, 0x33, 0x4f, 0x0b, 0x83, 0x34, 0x4b, 0x44, 0x32, 0xfb, 0x4c, 0x8e,
	0x31, 0x4e, 0xe5, 0x7f, 0xe2, 0xcb, 0x1f, 0xb6, 0x04, 0xff, 0x25, 0xcf, 0x92, 0x33, 0xf0, 0xe2,
	0x88, 0x36, 0xc7, 0xcd, 0xeb, 0x6e, 0xe8, 0xc5, 0x11, 0xb9, 0x04, 0x5f, 0xc4, 0x62, 0x87, 0xd4,
	0x93, 0x29, 0x15, 0xe4, 0xd9, 0x0f, 0xdc, 0x67, 0x48, 0x5b, 0x2a, 0x2b, 0x03, 0x76, 0x07, 0x64,
	0x99, 0xe1, 0x5a, 0xa0, 0x44, 0x85, 0xf8, 0x75, 0x40, 0x2e, 0x08, 0x03, 0x5f, 0x0e, 0x94, 0xd0,
	0xde, 0xbc, 0xaf, 0x06, 0x4f, 0x95, 0x46, 0x95, 0xd8, 0x3d, 0x0c, 0x4b, 0x9d, 0x3c, 0x4d, 0xf6,
	0x1c, 0x7f, 0xd5, 0xca, 0xe0, 0x22, 0xc4, 0x75, 0x54, 0x1a, 0x59, 0x59, 0x82, 0xdd, 0xc2, 0xc0,
	0xd2, 0x9c, 0x00, 0x1f, 0x5a, 0x8d, 0x5c, 0xd3, 0xd9, 0x03, 0x10, 0x3b, 0xa9, 0x71, 0x13, 0x68,
	0xcb, 0x1e, 0x4e, 0x9b, 0xe3, 0x96, 0xc3, 0xd3, 0xb5, 0xfc, 0x44, 0x6f, 0x69, 0xf4, 0xc7, 0x13,
	0x95, 0x3a, 0x4f, 0xd8, 0x62, 0x02, 0xe4, 0x09, 0x77, 0x58, 0x19, 0x5a, 0x3d, 0xd2, 0x0c, 0x86,
	0x25, 0x95, 0x1e, 0x40, 0xe1, 0x1f, 0x3f, 0x6c, 0xb7, 0xc8, 0xb9, 0xd4, 0x76, 0xc2, 0x22, 0x9c,
	0x7f, 0x7b, 0xd0, 0x97, 0xda, 0x57, 0xcc, 0x8e, 0xf1, 0x16, 0xc9, 0x0a, 0x7a, 0x96, 0x8b, 0x64,
	0xa4, 0x9f, 0xc5, 0x7d, 0x27, 0x82, 0xa0, 0xae, 0xa4, 0x06, 0xb2, 0x06, 0x79, 0x84, 0xce, 0x33,
	0x0a, 0x05, 0xb9, 0xd2, 0xca, 0xaa, 0xc7, 0x01, 0x75, 0x0b, 0x06, 0xb0, 0x80, 0x6e, 0x01, 0xe0,
	0xc4, 0x11, 0x16, 0x46, 0x06, 0xa3, 0x9a, 0x8a, 0x61, 0xac, 0xa0, 0x67, 0xdd, 0xdb, 0x2c, 0xe3,
	0xba, 0x67, 0x96, 0xa9, 0xb1, 0x47, 0x71, 0xac, 0xb3, 0x1a, 0x8e, 0x6b, 0x88, 0xe1, 0xd4, 0xb8,
	0xc0, 0x1a, 0x8b, 0xf3, 0xf7, 0xff, 0xd6, 0xd7, 0x9b, 0x6e, 0x36, 0x6d, 0x19, 0xde, 0xfc, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0x0f, 0xb7, 0x53, 0xd5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MovieServiceClient interface {
	CreateMovie(ctx context.Context, in *CreateMovieRequest, opts ...grpc.CallOption) (*CreateMovieResponse, error)
	GetMovie(ctx context.Context, in *ReadMovieRequest, opts ...grpc.CallOption) (*ReadMovieResponse, error)
	GetMovies(ctx context.Context, in *ReadMoviesRequest, opts ...grpc.CallOption) (*ReadMoviesResponse, error)
	UpdateMovie(ctx context.Context, in *UpdateMovieRequest, opts ...grpc.CallOption) (*UpdateMovieResponse, error)
	DeleteMovie(ctx context.Context, in *DeleteMovieRequest, opts ...grpc.CallOption) (*DeleteMovieResponse, error)
}

type movieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieServiceClient(cc grpc.ClientConnInterface) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) CreateMovie(ctx context.Context, in *CreateMovieRequest, opts ...grpc.CallOption) (*CreateMovieResponse, error) {
	out := new(CreateMovieResponse)
	err := c.cc.Invoke(ctx, "/proto.MovieService/CreateMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) GetMovie(ctx context.Context, in *ReadMovieRequest, opts ...grpc.CallOption) (*ReadMovieResponse, error) {
	out := new(ReadMovieResponse)
	err := c.cc.Invoke(ctx, "/proto.MovieService/GetMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) GetMovies(ctx context.Context, in *ReadMoviesRequest, opts ...grpc.CallOption) (*ReadMoviesResponse, error) {
	out := new(ReadMoviesResponse)
	err := c.cc.Invoke(ctx, "/proto.MovieService/GetMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) UpdateMovie(ctx context.Context, in *UpdateMovieRequest, opts ...grpc.CallOption) (*UpdateMovieResponse, error) {
	out := new(UpdateMovieResponse)
	err := c.cc.Invoke(ctx, "/proto.MovieService/UpdateMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) DeleteMovie(ctx context.Context, in *DeleteMovieRequest, opts ...grpc.CallOption) (*DeleteMovieResponse, error) {
	out := new(DeleteMovieResponse)
	err := c.cc.Invoke(ctx, "/proto.MovieService/DeleteMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
type MovieServiceServer interface {
	CreateMovie(context.Context, *CreateMovieRequest) (*CreateMovieResponse, error)
	GetMovie(context.Context, *ReadMovieRequest) (*ReadMovieResponse, error)
	GetMovies(context.Context, *ReadMoviesRequest) (*ReadMoviesResponse, error)
	UpdateMovie(context.Context, *UpdateMovieRequest) (*UpdateMovieResponse, error)
	DeleteMovie(context.Context, *DeleteMovieRequest) (*DeleteMovieResponse, error)
}

// UnimplementedMovieServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMovieServiceServer struct {
}

func (*UnimplementedMovieServiceServer) CreateMovie(ctx context.Context, req *CreateMovieRequest) (*CreateMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMovie not implemented")
}
func (*UnimplementedMovieServiceServer) GetMovie(ctx context.Context, req *ReadMovieRequest) (*ReadMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovie not implemented")
}
func (*UnimplementedMovieServiceServer) GetMovies(ctx context.Context, req *ReadMoviesRequest) (*ReadMoviesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovies not implemented")
}
func (*UnimplementedMovieServiceServer) UpdateMovie(ctx context.Context, req *UpdateMovieRequest) (*UpdateMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMovie not implemented")
}
func (*UnimplementedMovieServiceServer) DeleteMovie(ctx context.Context, req *DeleteMovieRequest) (*DeleteMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMovie not implemented")
}

func RegisterMovieServiceServer(s *grpc.Server, srv MovieServiceServer) {
	s.RegisterService(&_MovieService_serviceDesc, srv)
}

func _MovieService_CreateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).CreateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MovieService/CreateMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).CreateMovie(ctx, req.(*CreateMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MovieService/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).GetMovie(ctx, req.(*ReadMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_GetMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMoviesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).GetMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MovieService/GetMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).GetMovies(ctx, req.(*ReadMoviesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_UpdateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).UpdateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MovieService/UpdateMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).UpdateMovie(ctx, req.(*UpdateMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_DeleteMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).DeleteMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MovieService/DeleteMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).DeleteMovie(ctx, req.(*DeleteMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMovie",
			Handler:    _MovieService_CreateMovie_Handler,
		},
		{
			MethodName: "GetMovie",
			Handler:    _MovieService_GetMovie_Handler,
		},
		{
			MethodName: "GetMovies",
			Handler:    _MovieService_GetMovies_Handler,
		},
		{
			MethodName: "UpdateMovie",
			Handler:    _MovieService_UpdateMovie_Handler,
		},
		{
			MethodName: "DeleteMovie",
			Handler:    _MovieService_DeleteMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/movie.proto",
}
